[[main]]
  name = "BLOG"
  url = "post/"
  weight = 20

[[main]]
  name = "TALKS"
  url = "talk/"
  weight = 30

[[main]]
  name = "PROJECTS"
  url = "project/"
  weight = 50

[[main]]
  name = "ABOUT / CONTACT"
  url = "contact/"
  weight = 60
